<?php

namespace AppBundle\Repository;

/**
 * ThematiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThematiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
