AppBundle\Entity\Reponse:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ReponseRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        reponse:
            type: string
            length: 255
        correct:
            type: boolean
        commentaire:
            type: string
            length: 255
    lifecycleCallbacks: {  }
    manyToOne:
      question:
        targetEntity: Question
        inversedBy: reponses
        joinColumn:
          name: question_id
          referencedColumnName: id
      examen:
        targetEntity: Examen
        inversedBy: reponses
        joinColumn:
          name: examen_id
          referencedColumnName: id
